[target.aarch64-linux-android]
linker = "C:\\Users\\legoc\\AppData\\Local\\Android\\Sdk\\ndk\\29.0.13846066\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android24-clang.cmd"

[target.aarch64-apple-darwin]
linker = "/usr/bin/cc"
ar = "/opt/local/bin/ar"

[target.x86_64-apple-darwin]
linker = "/usr/bin/cc"
ar = "/opt/local/bin/ar"



